<div id="page-heading"><h1><?php echo $this->placeholder('heading'); ?></h1></div>
<table border="0" width="100%" cellpadding="0" cellspacing="0" id="content-table">
    <tr>
        <th rowspan="3" class="sized"><img src="/images/shared/side_shadowleft.jpg" width="20" height="300" alt="" /></th>
        <th class="topleft"></th>
        <td id="tbl-border-top">&nbsp;</td>
        <th class="topright"></th>
        <th rowspan="3" class="sized"><img src="/images/shared/side_shadowright.jpg" width="20" height="300" alt="" /></th>
    </tr>
    <tr>
        <td id="tbl-border-left"></td>
        <td>
            <div id="content-table-inner">
                <table border="0" width="100%" cellpadding="0" cellspacing="0">
                    <tr valign="top">
                        <td>
                            <form method="post" id="company-form">
                                <table border="0" cellpadding="0" cellspacing="0"  id="id-form">
                                    <tr>
                                        <th valign="top"><?php echo $this->translate('Company name'); ?>:</th>
                                        <td class="form-float-left"><?php echo $this->form->name; ?></td>
                                        <td></td>
                                    </tr>
                                    <?php if ($this->action() == 'edit') { ?>
                                        <tr>
                                            <th valign="top"><?php echo $this->translate('Status'); ?>:</th>
                                            <td class="form-float-left"><?php echo $this->form->status; ?></td>
                                            <td></td>
                                        </tr>
                                    <?php } ?>
                                    <tr>
                                        <th>&nbsp;</th>
                                        <td valign="top">
                                            <input type="submit" value="<?php echo $this->translate('Submit'); ?>" class="form-submit" />
                                            <input type="reset" value="<?php echo $this->translate('Back'); ?>" class="form-reset" onClick="window.back()" />
                                        </td>
                                        <td></td>
                                    </tr>
                                </table>
                            </form>
                        </td>
                        <?php if ($this->action() == 'edit') { ?>
                            <td>
                                <div id="related-activities">
                                    <div id="related-act-top">
                                        <img src="/images/forms/header_related_act.gif" width="271" height="43" alt="" />
                                    </div>
                                    <div id="related-act-bottom">
                                        <div id="related-act-inner">
                                            <div class="left"><img src="/images/forms/icon_minus.gif" width="21" height="21" alt="" /></div>
                                            <div class="right">
                                                <h5><?php echo $this->translate('Delete company'); ?></h5>
                                                <?php echo $this->translate("All information related to this company will be removed."); ?>
                                                <ul class="greyarrow">
                                                    <li><a href="javascript:void(0)" onClick="deleteCompany()"><?php echo $this->translate('Click here to remove'); ?></a></li> 
                                                </ul>
                                            </div>
                                            <div class="clear"></div>
                                        </div>
                                        <div class="clear"></div>
                                    </div>
                                </div>
                            </td>
                        <?php } ?>
                    </tr>
                    <tr>
                        <td><img src="/images/shared/blank.gif" width="695" height="1" alt="blank" /></td>
                        <td></td>
                    </tr>
                </table>
                <div class="clear"></div>
            </div>
        </td>
        <td id="tbl-border-right"></td>
    </tr>
    <tr>
        <th class="sized bottomleft"></th>
        <td id="tbl-border-bottom">&nbsp;</td>
        <th class="sized bottomright"></th>
    </tr>
</table>
<div class="clear">&nbsp;</div>
<?php if ($this->action() == 'edit') { ?>
    <div id="company-delete" class="dialog-box display-none">
        <table>
            <tr>
                <td>
                    <?php echo $this->translate('There may be product models associated with the company. Do you want to keep them or delete them?'); ?>
                </td>
            </tr>
            <tr><td>&nbsp;</td></tr>
            <tr>
                <td valign="middle">
                    <form id="company-delete-form" method="post" action="<?php echo $this->url(array('action' => 'delete')); ?>">
                        <input type="checkbox" name="delete_models" class="checkbox-size"/>
                        <label for="delete_models"><?php echo $this->translate('Delete associated models'); ?></label>
                    </form>
                </td>
            </tr>
        </table>
    </div>
    <script>
        function deleteCompany(){
            $('#company-delete').dialog({
                modal: true,
                draggable: false,
                resizable: false,
                title: "<?php echo $this->translate('Delete company'); ?>",
                buttons: [
                    {
                        text: "<?php echo $this->translate('Ok'); ?>",
                        click: function() {
                            //Action
                            $("#company-delete-form").submit();
                        }
                    },
                    {
                        text: "<?php echo $this->translate('Cancel'); ?>",
                        click: function() {
                            $(this).dialog("close");
                        }
                    }
                ]
            });
        }
    </script>
    <?php
}