<div id="page-heading">
    <h1><?php echo $this->placeholder('heading'); ?></h1>
</div>
<table border="0" width="100%" cellpadding="0" cellspacing="0" id="content-table">
    <tr>
        <th rowspan="3" class="sized">
            <img src="/images/shared/side_shadowleft.jpg" width="20" height="300" alt="" />
        </th>
        <th class="topleft"></th>
        <td id="tbl-border-top">&nbsp;</td>
        <th class="topright"></th>
        <th rowspan="3" class="sized"><img src="/images/shared/side_shadowright.jpg" width="20" height="300" alt="" /></th>
    </tr>
    <tr>
        <td id="tbl-border-left"></td>
        <td>
            <div id="content-table-inner">
                <?php if ($this->customerSales) { ?>
                    <table border="0" width="100%" cellpadding="0" cellspacing="0">
                        <tr valign="top">
                            <td>
                                <table border="0" cellpadding="0" cellspacing="0" width="50%" id="id-form" style="margin-left:10px">
                                    <tr>
                                        <th valign="top"><?php echo $this->translate('Total sales'); ?>:</th>
                                        <td class="form-float-left"><?php echo $this->salesStats['sales_count']; ?></td>
                                    </tr>
                                    <tr>
                                        <th valign="top"><?php echo $this->translate('Amount payable'); ?>:</th>
                                        <td class="form-float-left"><?php echo (float) $this->salesStats['payable_amount']; ?></td>
                                    </tr>
                                    <tr>
                                        <th valign="top"><?php echo $this->translate('Amount payed'); ?>:</th>
                                        <td class="form-float-left"><?php echo (float) $this->salesStats['payed_amount']; ?></td>
                                    </tr>
                                    <tr>
                                        <th valign="top"><?php echo $this->translate('Balance'); ?>:</th>
                                        <td class="form-float-left"><?php echo ((float) $this->salesStats['payable_amount']) - ((float) $this->salesStats['payed_amount']); ?></td>
                                    </tr>
                                    <tr>
                                        <th valign="top"><?php echo $this->translate('Last sale'); ?>:</th>
                                        <td class="form-float-left"><?php echo (!empty($this->salesStats['last_sale']) ? $this->salesStats['last_sale'] : $this->translate('None')); ?></td>
                                    </tr>
                                </table>
                            </td>
                    </table>
                <?php } ?>
                <div id="table-content">
                    <div id="sale-search-tool" class="position-relative search-tool">
                        <?php if ($this->searched == TRUE) { ?>
                            <a class="icon-delete float-right" onClick="clearSaleSearch()"></a>
                        <?php } ?>
                        <a class="icon-search float-right <?php echo ($this->searched == TRUE ? 'icon-search-selected' : ''); ?>" onClick="toggleSaleSearch()"></a>
                        <div class="clear"></div>
                    </div>
                    <form method="post" id="sale-search-form">
                        <table border="0" width="100%" cellpadding="0" cellspacing="0" id="product-table">
                            <tr>
                                <?php if ($this->customerSales != TRUE) { ?>
                                    <th class="table-header-repeat line-left"><?php $this->sortOrder('customer_name', $this->translate('Customer')); ?></th>
                                <?php } ?>
                                <th class="table-header-repeat line-left"><?php $this->sortOrder('products_count', $this->translate('Products')); ?></th>
                                <th class="table-header-repeat line-left"><?php $this->sortOrder('payable_amount', $this->translate('Amount payable')); ?></th>
                                <th class="table-header-repeat line-left" style="text-align:center"><span class="ui-icon ui-icon-arrowthick-1-s" title="<?php echo $this->translate('Concession'); ?>" style="display:inline-block"></span></th>
                                <th class="table-header-repeat line-left"><?php $this->sortOrder('payed_amount', $this->translate('Amount payed')); ?></th>
                                <th class="table-header-repeat line-left"><?php $this->sortOrder('remaining_balance', $this->translate('Remaining balance')); ?></th>
                                <th class="table-header-repeat line-left"><?php $this->sortOrder('on_hold', $this->translate('On hold')); ?></th>
                                <th class="table-header-repeat line-left"><?php $this->sortOrder('created_at', $this->translate('Date of creation')); ?></th>
                                <th class="table-header-options line-left"><a href="javascript:void(0)"><?php echo $this->translate('Options'); ?></a></th>
                            </tr>
                            <tr id="sale-search-row" class="search-row <?php echo ($this->searched == TRUE ? '' : 'display-none'); ?>">
                                <?php if ($this->customerSales != TRUE) { ?>
                                    <td><div><?php echo $this->filter->customer_name; ?></div></td>
                                <?php } ?>
                                <td colspan="5"><div><?php echo $this->filter->type; ?></div></td>
                                <td><div><?php echo $this->filter->on_hold; ?></div></td>
                                <td><div><?php echo $this->filter->created_at_from; ?><?php echo $this->filter->created_at_to; ?></div></td>
                                <td class="options-width">
                                    <a href="javascript:void(0)" title="<?php echo $this->translate('Search'); ?>" class="icon-tick" onClick="searchSale()"></a>
                                </td>
                            </tr>
                            <?php if (count($this->paginator)) { ?>
                                <?php foreach ($this->paginator as $key => $sale) { ?>
                                    <tr <?php echo ($key % 2 == 0 ? 'alternate-row' : ''); ?>>
                                        <?php if ($this->customerSales != TRUE) { ?>
                                            <td><a href="<?php echo $this->url(array('module' => 'sales', 'id' => $sale['customer_id'])); ?>"><?php echo $sale['customer_name']; ?></a></td>
                                        <?php } ?>
                                        <?php if ($sale['payable_amount'] > 0) { ?>
                                            <td><?php echo $sale['products_count']; ?></td>
                                            <td><?php echo $sale['payable_amount']; ?></td>
                                            <td><?php echo $sale['concession']; ?></td>
                                        <?php } else { ?>
                                            <td colspan="3" align="middle">(<?php echo $this->translate('Payment'); ?>)</td>
                                        <?php } ?>
                                        <td><?php echo $sale['payed_amount']; ?></td>
                                        <?php if ($sale['payable_amount'] > 0) { ?>
                                            <td><?php echo $sale['remaining_balance']; ?></td>
                                        <?php } else { ?>
                                            <td align="middle">(<?php echo $this->translate('Payment'); ?>)</td>
                                        <?php } ?>
                                        <td><?php echo $sale['on_hold']; ?></td>
                                        <td><?php echo $sale['created_at']; ?></td>
                                        <td class="options-width">
                                            <a href="<?php echo $this->url(array('module' => 'sales', 'action' => 'detail', 'id' => $sale['id'])); ?>" title="<?php echo $this->translate('Detail'); ?>" class="icon-detail"></a>
                                        </td>
                                    </tr>
                                <?php } ?>
                            <?php } else { ?>
                                <tr>
                                    <td colspan="<?php echo ($this->customerSales == TRUE ? 8 : 9); ?>" class="no-results"><?php echo $this->translate('No results found'); ?></td>
                                </tr>
                            <?php } ?>
                        </table>
                    </form>
                </div>
                <?php echo $this->paginationControl($this->paginator, 'Sliding', 'paging-table.phtml'); ?>
                <div class="clear"></div>
            </div>
        </td>
        <td id="tbl-border-right"></td>
    </tr>
    <tr>
        <th class="sized bottomleft"></th>
        <td id="tbl-border-bottom">&nbsp;</td>
        <th class="sized bottomright"></th>
    </tr>
</table>
<div class="clear">&nbsp;</div>
<script>
    function toggleSaleSearch(){
        $("#sale-search-tool .icon-search").toggleClass('icon-search-selected');
        $("#sale-search-row").toggle();
    }
    
    function searchSale(){
        var input = $("#sale-search-row input,#sale-search-row select");
        var formEmpty = true;
        $.each(input,function(index,obj){
            if($(obj).val() != ''){
                formEmpty = false;
            }
        });
        if(formEmpty == false){
            $('#sale-search-form').submit();
        }
    }
    
    function clearSaleSearch(){
        window.location.href = '<?php echo $this->url(array('module' => 'sales', 'id' => $this->customerId), NULL, TRUE); /* ($this->customerSales === TRUE ? $this->customerId : NULL) */ ?>';
    }
    
    $(function(){
        $(".datepicker").datepicker({dateFormat: "yy-mm-dd"});
    });
</script>