<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <?php /* <title>Internet Dreams</title> */ ?>
        <?php echo $this->headTitle(); ?>
        <link rel="stylesheet" href="<?php echo $this->getResource('css/screen.css'); ?>" type="text/css" media="screen" title="default" />

        <script src="<?php echo $this->getResource('js/jquery-1.9.1.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->getResource('js/custom_jquery.js'); ?>" type="text/javascript"></script>

        <!-- MUST BE THE LAST SCRIPT IN <HEAD></HEAD></HEAD> png fix -->
        <script src="<?php echo $this->getResource('js/jquery.pngFix.pack.js'); ?>" type="text/javascript"></script>
        <script type="text/javascript">
            $(document).ready(function(){
                $(document).pngFix( );
            });
        </script>
    </head>
    <body id="login-bg">
        <div id="alert-messages"><?php echo $this->alertMessages(); ?></div>
        <div id="login-holder">
            <div id="logo-login">
                <a href="<?php echo $this->baseUrl(); ?>/"><img src="<?php echo $this->baseUrl(); ?>/images/shared/logo.png" width="156" height="40" alt="" /></a>
            </div>
            <div class="clear"></div>
            <?php echo $this->layout()->content; ?>
        </div>
    </body>
</html>